### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [parasop/poru-example#4]
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: [Poru Connection] you have to Provide guildId

**Comment by parasop** [comment]
Fixed

**Comment by ghost** [comment]
when i run bot i have a problems 
`node:events:505`
`      throw er; // Unhandled 'error' event`
`  --^`
`TypeError: Cannot read properties of undefined (reading 'get')`
`    at module.exports.run (D:\Downloads\poru-example-main_2\poru-example-main\events\interactionCreate.js:5:34)`
and i changed `const command = client.slash.get(interaction.commandName);` in interactionCreate.js to `const command = client.commands.get(interaction.commandName);`  the error has been fixed but it appears 1 more error that is `const resolve = await client.poru.resolve(args.join(' '));`
`--------------------------------^`

`TypeError: Cannot read properties of undefined (reading 'join')`
  `  at Object.run (D:\Downloads\poru-example-main_2\poru-example-main\commands\Music\play.js:15:52)`
`    at module.exports.run (D:\Downloads\poru-example-main_2\poru-example-main\events\interactionCreate.js:35:15)`

**Comment by parasop** [comment]
Again fixed

**Comment by ghost** [comment]
you forger change slashCommands in handler/slash.js to slash :v

**Comment by ghost** [comment]
`D:\Downloads\poru-example-main_3\poru-example-main\events\voiceStateUpdate.js:5`
  `if (!newVoice.guild.me.voice.channel) {`
`-------------------------^`

`TypeError: Cannot read properties of undefined (reading 'voice')`
:v

**Comment by parasop** [comment]
Try now we fixed all issues
